[2019-04-23 16:54:07] app.ERROR: Data from PrestaShop Addons is invalid, and cannot fallback on cache.  {"exception":"cURL error 28: Operation timed out after 5048 milliseconds with 137395 bytes received"} []
